### Send a POST request to the server
POST http://localhost:5000/submit
Content-Type: application/json

{
    "name": "Fire Boy",
    "message": "Ennada Panra venna"
}

### get the request you dumb shit
GET http://localhost:5000/